// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFilesystemSource(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddFilesystemSource'](arg1, arg2, arg3, arg4);
}

export function BrowseDirectory(arg1, arg2) {
  return window['go']['main']['App']['BrowseDirectory'](arg1, arg2);
}

export function GetAllScanProgress() {
  return window['go']['main']['App']['GetAllScanProgress']();
}

export function GetAllTracks() {
  return window['go']['main']['App']['GetAllTracks']();
}

export function GetScanProgress(arg1) {
  return window['go']['main']['App']['GetScanProgress'](arg1);
}

export function GetSourceConfig(arg1) {
  return window['go']['main']['App']['GetSourceConfig'](arg1);
}

export function GetSourceRootPath(arg1) {
  return window['go']['main']['App']['GetSourceRootPath'](arg1);
}

export function GetSources() {
  return window['go']['main']['App']['GetSources']();
}

export function GetSupportedFormats() {
  return window['go']['main']['App']['GetSupportedFormats']();
}

export function GetTrack(arg1) {
  return window['go']['main']['App']['GetTrack'](arg1);
}

export function GetTrackFilePath(arg1) {
  return window['go']['main']['App']['GetTrackFilePath'](arg1);
}

export function GetTracksByAlbum(arg1) {
  return window['go']['main']['App']['GetTracksByAlbum'](arg1);
}

export function GetTracksByArtist(arg1) {
  return window['go']['main']['App']['GetTracksByArtist'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RemoveSource(arg1) {
  return window['go']['main']['App']['RemoveSource'](arg1);
}

export function ScanAllLibraries() {
  return window['go']['main']['App']['ScanAllLibraries']();
}

export function ScanLibrary(arg1) {
  return window['go']['main']['App']['ScanLibrary'](arg1);
}

export function SearchTracks(arg1) {
  return window['go']['main']['App']['SearchTracks'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function UpdateFilesystemSource(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateFilesystemSource'](arg1, arg2, arg3, arg4, arg5);
}
