// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {model} from '../models';

export function AddFilesystemSource(arg1:string,arg2:Array<string>,arg3:boolean,arg4:Array<string>):Promise<void>;

export function BrowseDirectory(arg1:string,arg2:string):Promise<dto.DirectoryContentsDTO>;

export function GetAllScanProgress():Promise<Record<string, dto.ScanProgressDTO>>;

export function GetAllTracks():Promise<Array<dto.TrackDTO>>;

export function GetScanProgress(arg1:string):Promise<dto.ScanProgressDTO>;

export function GetSourceConfig(arg1:string):Promise<model.SourceConfiguration>;

export function GetSourceRootPath(arg1:string):Promise<string>;

export function GetSources():Promise<Array<dto.SourceDTO>>;

export function GetSupportedFormats():Promise<Array<string>>;

export function GetTrack(arg1:string):Promise<dto.TrackDTO>;

export function GetTrackFilePath(arg1:string):Promise<string>;

export function GetTracksByAlbum(arg1:string):Promise<Array<dto.TrackDTO>>;

export function GetTracksByArtist(arg1:string):Promise<Array<dto.TrackDTO>>;

export function RemoveSource(arg1:string):Promise<void>;

export function ScanAllLibraries():Promise<void>;

export function ScanLibrary(arg1:string):Promise<void>;

export function SearchTracks(arg1:string):Promise<Array<dto.TrackDTO>>;

export function SelectDirectory():Promise<string>;

export function UpdateFilesystemSource(arg1:string,arg2:string,arg3:Array<string>,arg4:boolean,arg5:Array<string>):Promise<void>;
